controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

# Création d'une route qui n'est pas relier à une logique controller
api_login:
  path: /api/login
  methods: [POST]
