name: Full Process CI #nom de l'action

on: #à chaque 
  push: 
    branches-ignore: #sauf pour
      - "dependabot/**"

jobs: #fait 
  ci:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}
    strategy:
      matrix:
        php: [8.4]
        symfony: [7.2]

    steps: #Etapes :
      - uses: actions/checkout@v4 #Check le code sources

      - name: Setup PHP #installe php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          extensions: intl, mbstring, opcache, pdo_sqlite, apcu, pcov
          tools: symfony
          ini-values: memory_limit=3G
          coverage: pcov

      - name: Validate composer #installe composer
        run: composer validate

      - name: Install composer dependencies #install les dépendence de php
        run: composer install --no-interaction

      - name: Check Security issues #verifie les failles de sécurité sur chaque bundle/dépendence
        run: symfony security:check

      - name: Check ECS review #verifie si le code source contient des erreurs (erreurs de syntaxes, use en trop ect...)
        run: vendor/bin/ecs check src

      - name: Run Unit Tests #lance les tests unitaires 
        run: php bin/phpunit --testsuite=unit --coverage-clover coverage/cov-unit.xml

      - name: Run Functional Tests #lance les tests functionnels 
        run: php bin/phpunit --testsuite=functional --coverage-clover coverage/cov-functional.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: coverage/cov-unit.xml
            flags: unit
            name: codecov-umbrella